---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-test
  namespace: network-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: network-test
  template:
    metadata:
      labels:
        name: network-test
      annotations:
        k8s.v1.cni.cncf.io/networks: br100
    spec:
      containers:
        - name: centos
          image: centos
          command: ['sleep', 'infinity']
          env:
            - name: EXPORTED_VAR
              value: "testing the network"
