---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-test
  namespace: network-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: network-test
  template:
    metadata:
      labels:
        name: network-test
      annotations:
        k8s.v1.cni.cncf.io/networks: brkni100
    spec:
      containers:
        - name: centos
          image: quay.io/dhellmann/centos-test-image
          imagePullPolicy: Always
          command: ['/show_details.sh']
          env:
            - name: EXPORTED_VAR
              value: "testing the network"
