---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dbr-enp1s0-policy
spec:
  desiredState:
    interfaces:
      - name: dbr
        description: Linux bridge with enp1s0 as a port
        type: linux-bridge
        state: up
        ipv4:
          dhcp: true
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp1s0

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br100
  namespace: network-test
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br100
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "cnv-bridge",
      "bridge": "br100",
      "vlan": 100,
      "ipam": {}
    }'
