---
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brkni-policy
spec:
  desiredState:
    interfaces:
      - name: brkni
        description: Linux bridge with enp1s0 as a port
        type: linux-bridge
        state: up
        ipv4:
          # Setting enabled to false means the pod will come up without
          # trying to get an IP for the interface.
          enabled: false
          #dhcp: true
          #enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp1s0

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: brkni100
  namespace: network-test
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/brkni100
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "provisioning",
      "vlan": 100,
      "ipam": {}
    }
